# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
LoisteMinesweeperBundle:
    resource: "@LoisteMinesweeperBundle/Resources/config/routing.yml"
    prefix:   /