LoisteMinesweeperBundle_start:
    pattern:  /
    defaults: { _controller: LoisteMinesweeperBundle:Game:start }

LoisteMinesweeperBundle_makeMove:
    pattern: /makeMove
    defaults: { _controller: LoisteMinesweeperBundle:Game:makeMove}